package mover

import (
	"go/ast"
	"testing"
)

func TestBuildConstraintLinesFromAST(t *testing.T) {
	tests := []struct {
		name string
		src  string
		want []string
	}{
		{
			name: "no constraints",
			src:  "package p\n\nfunc Foo() {}\n",
		},
		{
			name: "go build constraint",
			src:  "//go:build linux\n\npackage p\n",
			want: []string{"//go:build linux"},
		},
		{
			name: "legacy build constraint",
			src:  "// +build linux darwin\n\npackage p\n",
			want: []string{"// +build linux darwin"},
		},
		{
			name: "go build constraint with tab",
			src:  "//go:build\tlinux\n\npackage p\n",
			want: []string{"//go:build\tlinux"},
		},
		{
			name: "legacy build constraint without space after slashes",
			src:  "//+build linux\n\npackage p\n",
			want: []string{"//+build linux"},
		},
		{
			name: "legacy build constraint with tab",
			src:  "// +build\tlinux\n\npackage p\n",
			want: []string{"// +build\tlinux"},
		},
		{
			name: "license then constraints",
			src:  "// Copyright 2026\n\n//go:build linux\n// +build linux\n\npackage p\n",
			want: []string{"//go:build linux", "// +build linux"},
		},
		{
			name: "stop at package",
			src:  "package p\n\n//go:build linux\nfunc Foo() {}\n",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, file := mustParse(t, tt.src)
			got := buildConstraintLinesFromAST(file)
			if !sameStringSlice(got, tt.want) {
				t.Fatalf("buildConstraintLinesFromAST() = %#v, want %#v", got, tt.want)
			}
		})
	}
}

func TestIsGenerated_ASTBased(t *testing.T) {
	// ast.IsGenerated is used in validateRenderOp; this test guards the AST path.
	_, gen := mustParse(t, "// Code generated by x; DO NOT EDIT.\n\npackage p\n")
	if !ast.IsGenerated(gen) {
		t.Fatal("generated marker not detected by ast.IsGenerated")
	}
	_, hand := mustParse(t, "// handwritten\n\npackage p\n")
	if ast.IsGenerated(hand) {
		t.Fatal("handwritten file detected as generated by ast.IsGenerated")
	}
}

func TestFileImportsC(t *testing.T) {
	_, f := mustParse(t, "package p\nimport \"C\"\nfunc UseC(){}\n")
	if !fileImportsC(f) {
		t.Fatal("import C not detected")
	}
	_, g := mustParse(t, "package p\nimport \"fmt\"\nfunc F(){ _ = fmt.Sprint(1) }\n")
	if fileImportsC(g) {
		t.Fatal("non-cgo file detected as cgo")
	}
}

func TestFileHasDotImport(t *testing.T) {
	_, f := mustParse(t, "package p\nimport . \"math\"\nfunc F(){ _ = Pi }\n")
	if !fileHasDotImport(f) {
		t.Fatal("dot import not detected")
	}
	_, g := mustParse(t, "package p\nimport m \"math\"\nfunc F(){ _ = m.Pi }\n")
	if fileHasDotImport(g) {
		t.Fatal("named import detected as dot import")
	}
}
